<?php

Asset::set($url->protocol . 'maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css', 20);

Asset::set(__DIR__ . DS . 'asset' . DS . 'css' . DS . 'normal.min.css', 20);
Asset::set(__DIR__ . DS . 'asset' . DS . 'js' . DS . 'normal.min.js', 20);

// Manual page excerpt feature
if (!Plugin::exist('excerpt')) {
    Hook::set('page.excerpt', function($content, $lot = [], $that) use($language) {
        $s = Page::open($lot['path'])->get([
            'description' => null,
            'content' => null,
            'url' => null
        ]);
        $c = $that->get('content');
        // Excerpt cropper does not exist, return the page description
        // If page description is empty, return a fake excerpt generated by the page content
        if (!$c || strpos($c, '<!-- cut -->') === false) {
            return $that->description ?: To::snippet($c);
        }
        // Return the first part!
        return trim(explode('<!-- cut -->', $c)[0]) . '<p>' . HTML::a($language->article_continue, $that->get('url')) . '</p>';
    });
}